<template>
  <div class="app-container report-page">
    <!-- 搜索 -->
    <el-form :model="queryParams" :inline="true" label-width="70px">
      <el-form-item label="类型" prop="reportType">
        <el-select v-model="queryParams.reportType" placeholder="全部" clearable style="width:130px">
          <el-option v-for="t in typeOpts" :key="t.v" :label="t.label" :value="t.v"/>
        </el-select>
      </el-form-item>
      <el-form-item>
        <el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button>
        <el-button icon="Refresh" @click="resetQuery">重置</el-button>
      </el-form-item>
    </el-form>

    <!-- 生成按钮 -->
    <el-row :gutter="10" class="mb8">
      <el-col :span="1.5">
        <el-button type="primary" plain icon="Plus" @click="showGenDialog = true" v-hasPermi="['apms:report:generate']">
          生成新报告
        </el-button>
      </el-col>
    </el-row>

    <!-- 主从两栏 -->
    <el-row :gutter="16">
      <!-- 左：报告列表 -->
      <el-col :span="10">
        <div class="panel-title">
          <span>PDF 报告</span>
          <span class="panel-sub">共 {{ total }} 份 · 历史可复现</span>
        </div>
        <el-table :data="reportList" border stripe highlight-current-row
                  v-loading="loading" max-height="600" @row-click="handleRowClick">
          <el-table-column label="#" prop="id" width="50" align="center"/>
          <el-table-column label="类型" width="110">
            <template #default="scope">
              <el-tag :type="typeTag(scope.row.reportType)" size="small" effect="dark">
                {{ typeLabel(scope.row.reportType) }}
              </el-tag>
            </template>
          </el-table-column>
          <el-table-column label="主体" min-width="140">
            <template #default="scope">
              <span class="subject">{{ scope.row.athleteName || scope.row.taskName || scope.row.deptName || '—' }}</span>
            </template>
          </el-table-column>
          <el-table-column label="生成时间" width="160">
            <template #default="scope">{{ formatDateTime(scope.row.generateTime) }}</template>
          </el-table-column>
          <el-table-column label="版本" width="80" align="center">
            <template #default="scope" class="ver">{{ scope.row.templateVersion }}</template>
          </el-table-column>
          <el-table-column label="操作" width="120" fixed="right">
            <template #default="scope">
              <el-button link type="primary" icon="Download" @click.stop="handleDownload(scope.row)" v-hasPermi="['apms:report:download']">
                下载
              </el-button>
              <el-button link type="danger" icon="Delete" @click.stop="handleDelete(scope.row)" v-hasPermi="['apms:report:remove']">删</el-button>
            </template>
          </el-table-column>
        </el-table>
        <pagination v-show="total>0" :total="total" v-model:page="queryParams.pageNum" v-model:limit="queryParams.pageSize" @pagination="getList"/>
      </el-col>

      <!-- 右：详情侧栏 -->
      <el-col :span="14">
        <div class="panel-title">
          <span>报告详情</span>
          <span v-if="current" class="panel-sub">{{ typeLabel(current.reportType) }} · {{ current.generateTime }}</span>
          <span v-else class="panel-sub muted">← 点击左侧报告查看</span>
        </div>

        <div v-if="current" class="detail-panel">
          <!-- 头部 -->
          <div class="report-header" :class="'header-' + current.reportType">
            <div class="report-id">#{{ current.id }}</div>
            <div class="report-title">{{ typeLabel(current.reportType) }}</div>
            <div class="report-meta">
              <span v-if="current.athleteName">Athlete: <b>{{ current.athleteName }} ({{ current.athleteGender }}/{{ current.athleteTeam }})</b></span>
              <span v-if="current.taskName">Task: <b>{{ current.taskName }}</b></span>
              <span v-if="current.deptName">Team: <b>{{ current.deptName }}</b></span>
            </div>
            <div class="report-meta small">
              Generated by {{ current.generateBy }} @ {{ formatDateTime(current.generateTime) }} · Template {{ current.templateVersion }}
            </div>
          </div>

          <!-- 文件状态 -->
          <div class="file-status">
            <el-icon class="file-icon-doc"/><span class="file-name">{{ current.filePath?.split('/').pop() || '未生成' }}</span>
            <el-tag v-if="current.filePath" type="success" size="small">PDF Ready</el-tag>
            <el-tag v-else type="info" size="small">No File</el-tag>
          </div>

          <!-- JSON 快照（预览） -->
          <div class="section-title">
            Data Snapshot 🔒
            <span class="privacy-note">历史不漂移 · 可复现</span>
          </div>
          <div class="snapshot-box">
            <pre>{{ formatSnapshot(current.contentSnapshot) }}</pre>
          </div>

          <!-- 下载 -->
          <div v-if="current.filePath" class="download-bar">
            <el-button type="primary" icon="Download" @click="handleDownload(current)" v-hasPermi="['apms:report:download']">
              下载 PDF 报告
            </el-button>
            <span class="file-path">{{ current.filePath }}</span>
          </div>
          <el-empty v-else description="PDF 文件未生成"/>
        </div>
        <div v-else class="detail-empty">
          <el-empty description="选择左侧报告查看详情"/>
        </div>
      </el-col>
    </el-row>

    <!-- ========== 生成 Dialog ========== -->
    <el-dialog title="生成新报告" v-model="showGenDialog" width="520px">
      <el-form :model="genForm" :rules="genRules" ref="genFormRef" label-width="100px">
        <el-form-item label="报告类型" prop="reportType">
          <el-radio-group v-model="genForm.reportType">
            <el-radio value="INDIVIDUAL">单人综合</el-radio>
            <el-radio value="TASK">任务报告</el-radio>
            <el-radio value="TEAM">队伍汇总</el-radio>
          </el-radio-group>
        </el-form-item>
        <el-form-item v-if="genForm.reportType === 'INDIVIDUAL'" label="运动员" prop="athleteId">
          <el-select v-model="genForm.athleteId" placeholder="选运动员" filterable style="width:100%">
            <el-option v-for="a in athleteOpts" :key="a.athleteId" :label="a.name + ' (' + a.name + ')'" :value="a.athleteId"/>
          </el-select>
        </el-form-item>
        <el-form-item v-if="genForm.reportType === 'TASK'" label="测试任务" prop="taskId">
          <el-select v-model="genForm.taskId" placeholder="选任务" filterable style="width:100%">
            <el-option v-for="t in taskOpts" :key="t.id" :label="t.taskName" :value="t.id"/>
          </el-select>
        </el-form-item>
        <el-form-item v-if="genForm.reportType === 'TEAM'" label="队伍" prop="deptId">
          <el-tree-select v-model="genForm.deptId" :data="deptOpts" filterable :props="{ label: 'deptName', value: 'deptId' }" style="width:100%"/>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="showGenDialog = false">取 消</el-button>
        <el-button type="primary" :loading="genLoading" @click="submitGen">生成</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup name="ApmsReport">
import { listReport, getReport, generateReport, delReport, downloadReportUrl } from '@/api/apms/report'
import { listTestTask } from '@/api/apms/testTask'
import { listAthlete } from '@/api/apms/athlete'
import { listDept } from '@/api/system/dept'
import { UploadFilled } from '@element-plus/icons-vue'

const { proxy } = getCurrentInstance()

// ========= 字典 =========
const typeOpts = [
  { v: 'INDIVIDUAL', label: '单人综合' },
  { v: 'TASK',       label: '任务报告' },
  { v: 'TEAM',       label: '队伍汇总' }
]
function typeLabel(t) { return typeOpts.find(x => x.v === t)?.label || t }
function typeTag(t) { return ({ INDIVIDUAL: 'primary', TASK: 'success', TEAM: 'warning' })[t] || 'info' }

// ========= 查询 =========
const loading = ref(false)
const reportList = ref([])
const total = ref(0)
const queryParams = reactive({ pageNum: 1, pageSize: 10, reportType: null })

function getList() {
  loading.value = true
  listReport(queryParams).then(r => { reportList.value = r.rows; total.value = r.total; loading.value = false })
}
function handleQuery() { queryParams.pageNum = 1; getList() }
function resetQuery() { proxy.resetForm('queryForm'); handleQuery() }

// ========= 辅助下拉 =========
const athleteOpts = ref([]), taskOpts = ref([]), deptOpts = ref([])
listAthlete({ pageNum: 1, pageSize: 300 }).then(r => { athleteOpts.value = r.rows || [] })
listTestTask({ pageNum: 1, pageSize: 200 }).then(r => { taskOpts.value = r.rows || [] })
listDept({ pageNum: 1, pageSize: 500 }).then(r => { deptOpts.value = r.data || [] })

// ========= 主从 =========
const current = ref(null)
function handleRowClick(row) {
  current.value = row
  getReport(row.id).then(r => { current.value = r.data })
}

// ========= 生成 =========
const showGenDialog = ref(false)
const genLoading = ref(false)
const genForm = reactive({ reportType: 'INDIVIDUAL', athleteId: null, taskId: null, deptId: null })
const genRules = {
  INDIVIDUAL: [{ required: true, message: '请选运动员', trigger: 'change' }],
  TASK:       [{ required: true, message: '请选测试任务', trigger: 'change' }],
  TEAM:       [{ required: true, message: '请选队伍', trigger: 'change' }]
}

function submitGen() {
  genLoading.value = true
  const params = { reportType: genForm.reportType }
  if (genForm.athleteId) params.athleteId = genForm.athleteId
  if (genForm.taskId) params.taskId = genForm.taskId
  if (genForm.deptId) params.deptId = genForm.deptId
  generateReport(params).then(() => {
    proxy.$modal.msgSuccess('报告生成成功 📄')
    showGenDialog.value = false
    getList()
  }).finally(() => { genLoading.value = false })
}

// ========= 操作 =========
function handleDownload(row) {
  // RuoYi 前端拦截器自动加 Token — 直接 window.open
  const token = localStorage.getItem('Admin-Token')
  if (token) {
    // 用 fetch 下载更可靠（带 Authorization header）
    fetch(downloadReportUrl(row.id), {
      headers: { 'Authorization': 'Bearer ' + token }
    }).then(r => r.blob()).then(blob => {
      const a = document.createElement('a')
      const url = URL.createObjectURL(blob)
      a.href = url; a.download = row.filePath?.split('/').pop() || 'report.pdf'
      a.click(); URL.revokeObjectURL(url)
    })
  } else {
    window.open(downloadReportUrl(row.id), '_blank')
  }
}

function handleDelete(row) {
  proxy.$modal.confirm('确认删除该报告？PDF 文件一并清理。').then(() => {
    delReport(row.id).then(() => {
      proxy.$modal.msgSuccess('已删除'); getList()
      if (current.value?.id === row.id) current.value = null
    })
  }).catch(() => {})
}

function formatSnapshot(snap) {
  if (!snap) return '(empty)'
  try {
    const obj = JSON.parse(snap)
    return JSON.stringify(obj, null, 2)
  } catch { return snap }
}
function formatDateTime(d) { if (!d) return ''; return String(d).substring(0, 19).replace('T', ' ') }

getList()
</script>

<style scoped>
.report-page { padding: 12px 16px; }
.panel-title {
  display: flex; align-items: center; gap: 10px;
  font-size: 15px; font-weight: 600; color: #1b4332;
  padding: 0 0 10px; border-bottom: 1px solid #ebeef5; margin-bottom: 12px;
}
.panel-sub { font-size: 12px; color: #909399; font-weight: 400; }
.panel-sub.muted { color: #c0c4cc; }

.subject { font-weight: 500; color: #303133; }
.ver { font-family: Menlo, monospace; color: #1b4332; }

/* 详情 */
.detail-panel { min-height: 500px; }
.detail-empty { min-height: 500px; display: flex; align-items: center; justify-content: center; }

.report-header {
  padding: 18px 20px; border-radius: 8px;
  margin-bottom: 14px;
}
.header-INDIVIDUAL { background: #ecf5ff; border: 1px solid #409eff; }
.header-TASK       { background: #f0f9eb; border: 1px solid #67c23a; }
.header-TEAM       { background: #fdf6ec; border: 1px solid #e6a23c; }

.report-id { font-size: 12px; color: #909399; margin-bottom: 4px; }
.report-title { font-size: 20px; font-weight: 700; color: #303133; margin-bottom: 6px; }
.report-meta { font-size: 13px; color: #606266; margin-bottom: 3px; }
.report-meta b { color: #1b4332; }
.report-meta.small { font-size: 11px; color: #909399; }

.file-status {
  display: flex; align-items: center; gap: 10px;
  padding: 10px 14px; background: #f6fbf7; border: 1px solid #d4e4d9; border-radius: 5px;
  margin-bottom: 14px;
}
.file-icon-doc { font-size: 24px; color: #1b4332; }
.file-name { font-weight: 500; color: #303133; flex: 1; }

.section-title {
  font-size: 13px; font-weight: 600; color: #1b4332;
  margin: 14px 0 8px; padding-left: 8px; border-left: 3px solid #1b4332;
  display: flex; align-items: center; gap: 8px;
}
.privacy-note { font-size: 11px; color: #67c23a; font-weight: 400; margin-left: auto; }

.snapshot-box {
  background: #1e1e1e; color: #d4d4d4;
  border-radius: 6px; padding: 12px 16px;
  font-family: Menlo, Consolas, monospace;
  font-size: 12px; line-height: 1.6;
  max-height: 280px; overflow: auto;
}
.snapshot-box pre { margin: 0; white-space: pre-wrap; word-break: break-all; }

.download-bar {
  margin-top: 14px; padding: 10px 14px;
  background: #ecf5ff; border: 1px solid #409eff; border-radius: 5px;
  display: flex; align-items: center; gap: 12px;
}
.file-path { font-size: 11px; color: #909399; font-family: Menlo; }
</style>
